worker_processes  1; # 分配几个CPU处理进程，根据服务器 CPU 核数调整，通常设置为 CPU 核数的 1-4 倍

events {
    worker_connections  1024; # 每个 worker 进程允许的最大连接数，根据服务器的实际资源和负载情况调整
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on; # 开启零拷贝传文件,提升静态文件性能
    keepalive_timeout  65; # 长连接超时 65 秒

    # Gzip 压缩（对静态文件和动态资源响应均生效），Nginx 会把要传输给浏览器的文本类文件先压缩，大幅减少传输的数据量
    gzip            on; # 开启 Gzip 压缩
    gzip_vary       on; # 告诉浏览器 / CDN：响应内容是否压缩过
    gzip_min_length 1024; # 只压缩大于 1KB 的文件
    # 指定要压缩的文件类型
    gzip_types      text/plain text/css
                    application/javascript text/javascript
                    application/json application/xml;

    # 通过uri -> 缓存规则的map映射，定义静态资源缓存规则
    map $uri $static_cache_control {
        # 第一条规则, 路径是以 js、css、png、jpg 这些后缀结尾的，不管大写小写，都给它分配 “缓存 1 天” 的规则, public: 浏览器、CDN 都可以缓存这个文件, max-age=86400：浏览器把这个文件存在本地 1 天
        ~*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$  "public, max-age=86400";
        # 第二条规则，请求的路径不是上面那些后缀（比如 .html、/chat 接口），每次用之前必须问服务器
        default                                          "no-cache";
    }

    server {
        listen 80;
        server_name www.yumt.site;

        # Vue 静态文件
        root /opt/smart_menu/ui/dist; # 静态资源根目录
        index index.html; # 默认首页

        # 静态资源路由
        # 前端路由（history 模式兜底）
        location / {
            # 按顺序检查文件或目录是否存在, $uri 表示查找与请求路径完全匹配的文件, $uri/ 表示请求对应目录, /index.html 是兜底文件
            try_files $uri $uri/ /index.html;
            # 控制浏览器和 CDN 的缓存策略, 由上方 map 根据文件后缀决定
            add_header Cache-Control $static_cache_control;
        }

        # 反向代理后端
        location /smart/menu/ {
            proxy_pass http://127.0.0.1:8000/smart/menu/;
            proxy_set_header Host $host; # 保持原始 Host, 让后端知道请求的域名
            proxy_set_header X-Real-IP $remote_addr; # 传递客户端真实 IP, 后端日志记录和安全策略需要
            proxy_set_header Cookie $http_cookie; # 传递 Cookie，保持会话(默认会透传请求头,可选)
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for; # 传递客户端 IP 列表，后端可以获取完整的访问链路
            proxy_set_header X-Forwarded-Proto $scheme;                 # 传递协议（http 或 https），后端可能需要根据协议生成正确的 URL
        }
    }
}